### ISSUE TITLE
Conturi de Heroku

### ISSUE THREAD

**Issue by tvararu** [tvararu/NEBUL4#4]
Am facut un schelet de baza al aplicatiei. Nu face aproape nimic deocamdata, dar are teste, si e deployata pe 2 servere:
- serverul de dezvoltare: [http://mds-dev.herokuapp.com](http://mds-dev.herokuapp.com)
- serverul de productie: [http://mds-prod.herokuapp.com](http://mds-prod.herokuapp.com), sau [http://mds.tvararu.ro](http://mds.tvararu.ro)

Mai trebuie sa scriu niste documentatie, dar puteti deja sa o clonati la voi local si sa incercati sa o rulati. Eventual sa schimbati din "hello world" in altceva (fisierul principal html e la `client/views/index.html`, dar nu pentru mult), sa rulati suita de teste si sa vedeti ca dă chix.

Ca sa puteti sa dati si voi pushuri pe serverele de dev/prod, am nevoie sa va faceti conturi la [Heroku](https://heroku.com). O data ce le aveti, lasati-le aici ca comentariu, si inchidem issue-ul cand se strang toate.

**Comment by raducc** [comment]
done

**Comment by tvararu** [comment]
Dupa ce va adaug la colaboratori, ca sa puteti sa impingeti schimbari pe aplicatia de pe Heroku, trebuie sa o adaugati la remote-urile de pe repo-ul local:

``` bash
$ cd proiect-mds
$ git remote add dev git@heroku.com:mds-dev.git
```

Apoi, puteti sa dati push in 2 directii. Una ar fi aici, pe Github, care merge cu:

``` bash
$ git push origin master
```

Si cealalta ar fi pe serverul de development, care merge cu:

``` bash
$ git push dev master
```
